### PR TITLE
Added custom units to amount selectors

### PR DESCRIPTION
**Pull request by johankristiansson**

### CODE REVIEW

**Comment by jonaskello** [comment]
The CI server runs combinations of node versions and typescript versions (see travis config [here](https://github.com/promaster-sdk/property/blob/master/.travis.yml)). Only two combinations fails as seen [here](https://travis-ci.com/promaster-sdk/property/builds/134017754). Perhaps something strange happened during the build. Have you tried re-running the build?

**Comment by jonaskello** [comment]
Seems only node 10 builds fails... not sure why though...

**Comment by jonaskello** [comment]
Seems like travis had some problems with their nvm install for different node versions. Restarted the failed jobs and now all travis jobs succeed. Only problem now is the test coverage is lower than expected. Not sure why it is reporting variant_listing as lower coverage. This PR should probably not affect the variant-listing package?

**Comment by jonaskello** [comment]
@johankristiansson I think you can go ahead and adjust the code coverage targets for react-properties-selector and variant-listing. Maybe set react-properties-selector to 65% and variant-listing to 45%. The settings are in the [codecov.yml](https://github.com/promaster-sdk/property/blob/master/codecov.yml) file. Once that is done I would expect this PR to be all green.

**Comment by jonaskello** [comment]
Not sure how codecov calculates their percentages :-/. I've set this repo up to use the [flags](https://docs.codecov.io/docs/flags) feature in codecov since it is a monorepo and it is nice to see the coverage per package. 

Seems the property package needs it's threshold updated now. I guess you can go ahead and set something like 50% for it.

**Comment by johankristiansson** [comment]
Seems like they are using the delicate and finely tuned Math.rand() algorithm or one of its derivatives.

**Comment by jonaskello** [comment]
Yeah, I guess just keep lowering the thresholds until it makes it thorough for now and we'll investigate later what is going on.

**Comment by johankristiansson** [comment]
Squashed the threshold commits.

**Comment by jonaskello** [comment]
If the threshold keeps causing problems you can merge it anyway. It does not affect anything, all tests are OK etc. only the calculated coverage seems off.

**Comment by jonaskello** [comment]
I've changed the travis config so it does only build only. Before it did one for the branch and one for the PR (see [this docs](https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests). I also removed the TSVERSION from the build matrix. Now it does only two builds, for node 10 and 12. This seemed to help a bit in keeping percentages constant.

**Comment by jonaskello** [comment]
Seems `codecov/patch` is failing now. If I understand [the docs](https://docs.codecov.io/docs/commit-status#section-patch-status) correctly it states how well tested lines added or changed by the PR are. Not sure if this PR adds or changes something that is not tested.

**Comment by jonaskello** [comment]
I disabled the codecov check for patch coverage for now. Now it seems to work as expected, just checking the total coverage for each package (ie. for each codecov flag).

**Pull request merged**
