### PR TITLE
Custom units

### PR DESCRIPTION
**Pull request by johankristiansson**
Upgraded `uom` and implemented custom units in amount selectors

### CODE REVIEW

**Comment by johankristiansson** [comment]
@jonaskello Seems like those snapshots are still haunting us...

**Comment by jonaskello** [comment]
Looking at https://travis-ci.com/promaster-sdk/property/jobs/246657899 I see this:

```
New snapshot was not written. The update flag must be explicitly passed to write a new snapshot. 
This is likely because this test is run in a continuous integration (CI) environment in which 
snapshots are not written by default.
```

I think you need to run the test locally once to create the snapshot file and then check that snapshot file into git?

**Comment by johankristiansson** [comment]
Running the tests locally does not yield any new snapshots.
Running `yarn run test:react-property-selectors -u` locally is the result of https://github.com/promaster-sdk/property/pull/1/commits/e51858da74ea2d39eff8d6ad50baa6248fe24873

**Comment by jonaskello** [comment]
Ok, so running `yarn run test:react-property-selectors -u` locally does not create any new snapshot files?

**Comment by johankristiansson** [comment]
That's right. The files did exist prior to https://github.com/promaster-sdk/property/commit/e51858da74ea2d39eff8d6ad50baa6248fe24873 but were removed by running `yarn run test:react-property-selectors -u` since they were identified by the tests to be obsolete.

**Comment by jonaskello** [comment]
Yes, they were obsolete because the tests they were for does not exist anymore (or they were renamed). However it should also have created a new snapshot file for the the tests that actually still exits. Not sure why it did not do that.

**Comment by jonaskello** [comment]
@johankristiansson I have fixed a lot of the jest config on master now, could you try re-basing on master again to see if it will work.

I think the root cause was that snapshots were written to `lib/` and therefore not added to git (but they existed locally so when running locally you get no errors about snapshots).

**Comment by johankristiansson** [comment]
Now we are getting even more errors.

**Comment by jonaskello** [comment]
Master works fine now. In master there is a snapshot file that is valid [here](https://github.com/promaster-sdk/property/tree/master/packages/react-property-selectors/src/__tests__/__snapshots__). This file seems to have been deleted from this branch and I think that is why CI fails. Not sure why it was deleted. Perhaps this branch has gotten too much out of sync with master?

One approach would be to re-branch from master and create a new PR with your changes. That way you should be able to see exactly what commit makes the CI fail (if any). Another way is of course to try and re-sync this PR with master.

**Comment by jonaskello** [comment]
Closing in favour of #7.

**Pull request closed without merging**
